'use strict';
//----------------------------------------------------------------
const errorCode = {
    VALIDATION_FAILED: "VALIDATION_FAILED",
    ERR_CREATE_ACCOUNT_FAILED: "ERR_CREATE_ACCOUNT_FAIL",
    DATA_CONFLICT: "DATA_CONFLICT",
    ERR_LOGIN_FAILED: "ERR_LOGIN_FAILED",
    DATA_NOT_FOUND: "DATA_NOT_FOUND",
    ACCOUNT_IS_BANNED: "ACCOUNT_IS_BANNED",
    UNAUTHORIZED: "UNAUTHORIZED",
    ERR_CREATE_ACCESS_TOKEN_FAILED: "ERR_CREATE_ACCESS_TOKEN_FAILED",
    EMAIL_SERVICE_UNAUTHORIZED: "EMAIL_SERVICE_UNAUTHORIZED",
    EMAIL_NOT_FOUND: "EMAIL_NOT_FOUND",
    ERR_GET_RESET_PASSWORD_LINK_FAILED: "ERR_GET_RESET_PASSWORD_LINK_FAILED",
    ERR_CHANGE_PASSWORD_FAILED: "ERR_CHANGE_PASSWORD_FAILED",
    ERR_CREATE_POST_FAILED: "ERR_CREATE_POST_FAILED",
    FILE_IS_NOT_SUPPORTED: "FILE_IS_NOT_SUPPORTED",
    UPLOAD_FILE_FAILED: "UPLOAD_FILE_FAILED",
    FILE_EXCEEDED_SIZE: "FILE_EXCEEDED_SIZE",
    ERR_DELETE_POST_FAILED: "ERR_DELETE_POST_FAILED",
    ERR_UPDATE_POST_FAILED: "ERR_UPDATE_POST_FAILED",
    ERR_GET_POST_FAILED: "ERR_GET_POST_FAILED",
    NOT_PERMISSIONS: "NOT_PERMISSIONS",
    CHECK_AUTHORIZATION_FAILED: "CHECK_AUTHORIZATION_FAILED",
    ERR_GET_DATA_FAILED: "ERR_GET_DATA_FAILED",
    ERR_ADD_FRIEND_FAILED: "ERR_ADD_FRIEND_FAILED",
    ERR_REMOVE_FRIEND_FAILED: "ERR_REMOVE_FRIEND_FAILED",
    ERR_RETRIEVE_FRIENDS_FAILED: "ERR_RETRIEVE_FRIENDS_FAILED"
};

const errorMessage = {
    EMAIL_EXISTED: "Email has existed already",
    USERNAME_EXISTED: "Username has existed already",
    UNKNOWN_ERROR: "Failure (unknown error)",
    DATA_NOT_FOUND: "Username or Password is not correct",
    ACCOUNT_IS_BANNED: "This account is banned",
    INVALID_TOKEN: "Invalid token",
    ERR_CREATE_ACCESS_TOKEN_FAILED: "Create access token failed",
    REFRESH_TOKEN_NOT_FOUND: "Refresh token not found",
    EMAIL_SERVICE_UNAUTHORIZED: "Email service is unauthorized",
    EMAIL_NOT_FOUND: "Email not found",
    ERR_GET_RESET_PASSWORD_LINK_FAILED: "Failure (reset password)",
    EXPIRED_TOKEN: "Expired token",
    ERR_CHANGE_PASSWORD_FAILED: "Failure (change password)",
    USER_NOT_FOUND: "User not found",
    ID_NOT_FOUND: "Id is required",
    FILE_EXCEEDED_SIZE: "File is exceeded (>=50)",
    UPLOAD_FILE_FAILED: "Upload file failed",
    POST_NOT_FOUND: "Post is not found",
    LOGIN_REQUIRED: "Login required",
    ERR_TOKEN_CAN_NOT_AUTHORIZE: "Error verifying access token",
    NOT_PERMISSIONS:  "You don't have permission to access this resource",
    ERR_INVALID_QUERY: "Query parameters is invalid",
    FRIEND_ALREADY_ADDED: "Friend already added",
    ID_CONFLICT: "Id can not be same as owner",
}

module.exports = { errorCode, errorMessage };
